### ISSUE TITLE
A valid token cannot be authorized.

### ISSUE THREAD

**Issue by hustshawn** [emanoelxavier/openid2go#22] opened 2018-03-22 10:07 UTC
The issue originate from Tyk, but finally as suggested by @buger ,the issue may come from your side.

Please refer to 
https://github.com/TykTechnologies/tyk/issues/1553#issuecomment-375226833

**Comment by emanoelxavier** [comment] 2018-03-26 02:18
@hustshawn @buger thx for raising the issue. I believe I was able to repro the problem using the integration tests. See: 
```
19:05 $ go test -tags integration github.com/emanoelxavier/openid2go/openid -issuer=http://idp-uat.ifund.com.hk/ -clientID=i12345678-idToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImkxMjM0NTY3OCJ9.eyJpc3MiOiJodHRwOi8vaWRwLXVhdC5pZnVuZC5jb20uaGsvIiwic3ViIjoiaTEyMzQ1Njc4IiwiaWF0IjoxNTIxNzA5NTE1LCJleHAiOjE1MjY4OTM1MTUsImF1ZCI6ImIyYiJ9.BiH0b_oLzWIqvMF8F2xfPDXwnBIqCiqtjzw3XzCjklHdXScN27m1gm2k3tK9hPEpNpEWknJUe8CneXBmalvnDOKqN0W8FyR5ats9wkAnrsto5NLeVPAWwhBlH_brsIkck5seCyAmp3rmTqKWNvEbfv8D1K1LX_Pd4u4FtJG3fI4Lb_BkhFz48sbTRP4rB0J7YgDoX6FCoiffAecR5aurLo7kLEz9dgD8irGG3a2VMh1cH0cPaEDyLQocY7D711_BtFiw_oEFGpUZ2c1MVB1nkBqCI6HHFpXI7ElWYZzXogz5vCWEZD39Z0H9H_tH6M8jOZ05A0uiEDnW1iIM-DkVvw
--- FAIL: Test_Authenticate_ValidIDToken (0.00s)
        integration_test.go:179: Expected response with prefix: Congrats, you are authenticated! but got: Validation error. The provider http://idp-uat.ifund.com.hk/ does not have a client id matching any of the token audiences [b2b]

        integration_test.go:185: Expected HTTP status 200 but got 401
--- FAIL: Test_AuthenticateUser_ValidIDToken (0.00s)
        integration_test.go:179: Expected response with prefix: Congrats, you are authenticated by the provider http://idp-uat.ifund.com.hk/! but got: Validation error. The provider http://idp-uat.ifund.com.hk/ does not have a client id matching any of the token audiences [b2b]

        integration_test.go:185: Expected HTTP status 200 but got 401
FAIL
FAIL    github.com/emanoelxavier/openid2go/openid       0.244s
```

If this is indeed the error then it is by design, according to OIDC the `aud` claim must have the client id:
```
aud
REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.
```
And when I look at the token I dont see that value:
```
{
  "iss": "http://idp-uat.ifund.com.hk/",
  "sub": "i12345678",
  "iat": 1521709515,
  "exp": 1526893515,
  "aud": "b2b"
}
```

So please check why the token is created without the client id in the aud. 

One thing that is not clear to me though is why the tests are returning an error different than what you have logged on the issue on your fork ("Jwt token validation failed with unknown error."). Is your fork up to date? Can you attempt the integration tests as well? 

Let me know if this helps. As far as I can tell this is not a bug on the package but I will wait for your reply before closing the issue.

**Comment by hustshawn** [comment] 2018-03-26 10:38
Hi @emanoelxavier , thanks for your reaching out. 
1. I understand OIDC need the client id as `aud`, and the value itself is a string. But it does not have to be the same as some other field, say `sub` in my token, or even the `kid`. What I used here is a little bit hack that I wanna make a group of client use the same `aud`, and identify each of them by `sub`. That's why the `b2b` comes in. Then do you think this is a legal way to do so? and what's your recommendation?
2.  The log is from Tyk, probably Tyk overwrite your log and makes it different with yours.  Also I am not sure whether Tyk community forked the update package, since OIDC lives behind the Tyk service.

**Comment by emanoelxavier** [comment] 2018-03-27 02:09
The client id you used to generate the token must be in the aud as per OIDC spec. The `aud` of your token right now has only this "aud": "b2b" . You may be able to group all the clients under the same `aud` but you need to have all the client ids in that audience as a list. See " It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences " . 

It seems strange to use the `sub` as a client id since it should represent the id of the OIDC identity (typically the end user). 

It should never pass, always fail. You can confirm that by running the integration test cmd I pasted above with the token. I am not sure though whether Tyk is caching any result and sometimes passing.

**Comment by emanoelxavier** [comment] 2018-03-30 01:06
Hi @hustshawn Is there still any aspect of this issue you would like to have fixed or do you have any further question? If not I will close the issue.

**Comment by hustshawn** [comment] 2018-04-02 03:44
@emanoelxavier  The "aud": "b2b"  is indeed what I used as client id,  also I think the value itself is valid no matter what it is exactly used and it should not affect the validation of this token, since the client id as what my IdP side configuration is the same as the token claims, say 'b2b' as 'aud'. 

It really happened that the token can not be passed the first time, then after some time it passed forever, that is what confuse me a lot. 

I am using Tyk which use your OIDC underground, so I have no way to your suggested test method to do the same as you did.

**Comment by emanoelxavier** [comment] 2018-04-02 13:35
This is the client id I saw logged in the Tyk issue -issuer=http://idp-uat.ifund.com.hk/ -clientID=**i12345678 **, so not b2b. According to the OIDC spec this id i12345678 must be included in the `aud` and it currently is not. So based on the spec the validation of the token must fail. To look at the contents of your token you can use www.jwt.io. 

To test this packaged without using Tyk should be easy, simply follow the steps https://github.com/emanoelxavier/openid2go#integration-tests

**Comment by hustshawn** [comment] 2018-04-04 03:50
@emanoelxavier so which claim in the token is recognised as the client Id? is it the `kid`? if so, does it mean the `kid` and `aud` should be the same value, since both of the value should be consistent to represent the client Id?

**Comment by emanoelxavier** [comment] 2018-04-04 13:34
As the OIDC spec the `aud` "MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences " . The `kid` is unrelated to this.

**Comment by emanoelxavier** [comment] 2018-04-05 02:03
@buger may be able to provide more details based on the origin of the token and its content. For a legitimate id token it must contain the client id in the audience. See details http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

**Comment by emanoelxavier** [comment] 2018-04-17 14:47
Hi @hustshawn do you still any additional question related to this problem? If not I will close the issue.

**Comment by hustshawn** [comment] 2018-04-18 08:37
Thank you @emanoelxavier very much. No more questions and you can close this issue.

**Closed** 2018-04-18 13:49 UTC
Labels: question
