### ISSUE TITLE
Inconsistent jwt.ValidationError in errors.go

### ISSUE THREAD

**Issue by rsoletob** [emanoelxavier/openid2go#8] opened 2016-09-06 10:22 UTC
In [errors.go](https://github.com/emanoelxavier/openid2go/blob/master/openid/errors.go#L94) there is a checking using two different types of ValidationError `github.com/dgrijalva/jwt-go` and `gopkg.in/dgrijalva/jwt-go.v2`.

This produces always a ValidationError with ValidationErrorJwtValidationUnknownFailure code and InternalServerError http status. Could you change go import from `github.com/dgrijalva/jwt-go` to `gopkg.in/dgrijalva/jwt-go.v2` in [errors.go](https://github.com/emanoelxavier/openid2go/blob/master/openid/errors.go#L7)?

Also we are losing the internal error because it doesn't set Err attribute in ValidationError struct.

**Comment by emanoelxavier** [comment] 2016-09-06 13:52
I am changing the code to use the latest version of the jwt package as part of the fix for #7.

**Comment by emanoelxavier** [comment] 2016-09-06 13:53
Closing a dupe of #7

**Closed by emanoelxavier** 2016-09-06 13:53 UTC
Labels: bug, duplicate
